"""
Helper for loading domain Q&A tasks generated by scripts/generate_domain_qa.py.
"""

import os
import glob

from tasks.customjson import CustomJSON


def get_domain_qa_tasks(base_dir, epochs=3):
    """Return list of Task objects for all domain Q&A corpora found in {base_dir}/domain_qa/."""
    qa_dir = os.path.join(base_dir, "domain_qa")
    tasks = []
    for jsonl_path in sorted(glob.glob(os.path.join(qa_dir, "*.jsonl"))):
        for _ in range(epochs):
            tasks.append(CustomJSON(filepath=jsonl_path))
    return tasks
